dismissal = {"Absent without leave (AWOL)":"Inactive",
"Client no show":"Inactive",
"Client not engaged within the past 30 days":"No longer meets population criteria",
"Criminal Activity/Destuction of Property/Violence":"No longer meets population criteria",
"Death":"No longer meets population criteria",
"Declined shelter placement/Remained homeless":"Inactive",
"Declined shelter placement/Resolved own situation":"Housed",
"Discharged for Non-Compliance":"No longer meets population criteria",
"Entered AAF":"Housed",
"Entered b2i Sullivan House":"Housed",
"Entered Doorways Family Home":"Housed",
"Entered HSC":"Housed",
"Entered RPC":"Housed",
"Eviction":"No longer meets population criteria",
"Exit to Permanent Housing":"Housed",
"Foster Care":"Housed",
"Graduated AAF":"Housed",
"Hospitilization":"Housed",
"Incarceration":"No longer meets population criteria",
"Left for Housing Opportunity":"Housed",
"Left Jurisdiction":"Inactive",
"Maximum Stay Allowed":"No longer meets population criteria",
"Non-Arlington Resident":"Inactive",
"Non-payment of Rent":"Inactive",
"Non-SMI":"Inactive",
"Red Line (90 day no contact / no interest in hsg)":"No longer meets population criteria",
"Removed from Pool":"No longer meets population criteria",
"Requested to leave by landlord":"No longer meets population criteria",
"Service Completed Successfully":"Housed",
"Transitional Housing":"Housed",
"Transitioned to Outpatient Services - SA":"Housed",
"Transitioned to Outpatient Services - Mental Health":"Housed",
"Transitioned to Senior Adult Mental Health":"Housed",
"Voluntary Departure":"Inactive"}