dismissal = {"Absent without leave (AWOL)":"Inactive",
"Client no show":"Inactive",
"Client not engaged within the past 30 days":"No longer meets population criteria",
"Client not engaged within the past 90 days":"No longer meets population criteria",
"Criminal Activity/Destruction of Property/Violence":"No longer meets population criteria",
"Death":"No longer meets population criteria",
"Declined shelter placement/Remained homeless":"Inactive",
"Declined shelter placement/Resolved own situation":"Housed",
"Resolved own homelessness":"Housed",
"Discharged for Non-Compliance":"No longer meets population criteria",
"Entered AAF":"Housed",
"Entered b2i Sullivan House":"Housed",
"Entered Doorways Family Home":"Housed",
"Entered HSC":"Housed",
"Entered RPC":"Housed",
"Eviction":"No longer meets population criteria",
"Exit to Permanent Housing":"Housed",
"Exit to RRH":"Housed",
"Exit to Shelter":"Housed",
"Foster Care":"Housed",
"Graduated AAF":"Housed",
"Hospital":"Housed",
"Hospitalization":"Housed",
"Incarceration":"No longer meets population criteria",
"Incarcerated":"No longer meets population criteria",
"Left for Housing Opportunity":"Housed",
"Left Jurisdiction":"Inactive",
"Maximum Stay Allowed":"No longer meets population criteria",
"Non-Arlington Resident":"Inactive",
"Non-payment of Rent":"Inactive",
"Non-SMI":"Inactive",
"Red Line (90 day no contact / no interest in hsg)":"No longer meets population criteria",
"Removed from Pool":"No longer meets population criteria",
"Requested to leave by landlord":"No longer meets population criteria",
"Service Completed Successfully":"Housed",
"Transitional Housing":"Housed",
"Transitioned to Aging & Disability":"Housed",
"Transitioned to Outpatient Services - SA":"Housed",
"Transitioned to Outpatient Services-Mental Health":"Housed",
"Transitioned to Senior Adult Mental Health":"Housed",
"Voluntary Departure":"Inactive",
"Moved to Arlington Zero Chronic Vet":"No longer meets population criteria",
"Moved to Arlington Zero Families":"No longer meets population criteria",
"Moved to Arlington Zero Singles":"No longer meets population criteria",
"Moved to Arlington Zero TAY":"No longer meets population criteria",
"Inappropriate Referral":"DHS,Bridges",
"Judged to be Ineligible for Service":"No longer meets population criteria",
"Other":"No longer meets population criteria",
"Refer to CE":"Inactive",
"Service not Available":"Inactive",
"Unknown":"Inactive",
"Completed Program":"Housed",
"Dropped Out":"Inactive",
"Moved":"Inactive",
"Non-Arlington Resident":"Inactive",
"Hotel/Motel":"Housed",
"Housing Grant":"Housed",
"Psychiatric Hospital or Psychiatric Facility":"Housed",
"Substance Abuse Treatment Facility or Detox Center":"Housed"}

to_be_added = {
    "Inappropriate Referral":"DHS,Bridges",
    "Judged to be Ineligible for Service":"DHS,Bridges",
    "Other":"DHS,Bridges",
    "Refer to CE":"DHS,Bridges",
    "Service not Available":"DHS,Bridges",
    "Unknown":"DHS,Bridges",
    "Completed Program":"Doorways",
    "Dropped Out":"Doorways",
    "Moved":"Doorways",
    "Non-Arlington Resident":"Doorways",
    "Hotel/Motel":"NHH",
    "Housing Grant":"NHH",
    "Psychiatric Hospital or Psychiatric Facility":"PathForward",
    "Substance Abuse Treatment Facility or Detox Center":"PathForward"
}

# dsort = sorted(dismissal)
# for i in dsort:
#     print(i)